#ifndef MIGRATION_OFFICE_CONFIGURATIONFILEFIELDS_H
#define MIGRATION_OFFICE_CONFIGURATIONFILEFIELDS_H

enum ALERTS_FIELDS {
    TIMESTAMP_POS,
    DEL_TIMESTAMP_POS,
    FEATURES_START_POS
};

#endif //MIGRATION_OFFICE_CONFIGURATIONFILEFIELDS_H
