#ifndef MIGRATION_OFFICE_STATISTICSDATA_H
#define MIGRATION_OFFICE_STATISTICSDATA_H

#include <cstddef>

static const size_t STATS_SIZE = 4;

enum FIELDS {
    ALLOWED_RESIDENTS,
    DETAINED_RESIDENTS,
    ALLOWED_FOREIGNERS,
    DEPORTED_FOREIGNERS
};
#endif //MIGRATION_OFFICE_STATISTICSDATA_H
